name: ThinkShout
description: ThinkShout - We provide web strategy and open source technology to forward-thinking organizations.
markdown: redcarpet
pygments: true

baseurl: /thinkshout
url: http://thinkshout.com

# Permalink Configuration
permalink: /blog/:year/:month/:title
