name: ThinkShout
description: ThinkShout - We provide web strategy and open source technology to forward-thinking organizations.
markdown: redcarpet
pygments: true

baseurl: /thinkshout
url: http://thinkshout.com

# Permalink Configuration
permalink: /blog/:year/:month/:title

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'bower.json', '.bowerrc', 'config.rb', 'sass']

# Team directory used by the data_to_pages plugin.
team_dir: 'team'

paginate: 1
paginate_path: "blog/page:num"